/* =====================================================================
   V4  --  schema changes from the code review
     - optimistic locking columns                      (7.8)
     - employee codes generated by the database        (5.5)
     - contracts keep their original end date          (10.5)
     - leave attachments + public holiday calendar     (10.3)
     - audit trail                                     (9.9)
     - refresh tokens + user disable flag              (9.5)
     - headcount view without a per-row function call  (performance)
   ===================================================================== */

SET NAMES utf8mb4;

/* ---- 7.8 optimistic locking ------------------------------------------ */
ALTER TABLE employees                  ADD COLUMN version INT NOT NULL DEFAULT 0;
ALTER TABLE employee_contracts         ADD COLUMN version INT NOT NULL DEFAULT 0;
ALTER TABLE employee_salary_components ADD COLUMN version INT NOT NULL DEFAULT 0;
ALTER TABLE leave_requests             ADD COLUMN version INT NOT NULL DEFAULT 0;
ALTER TABLE loans                      ADD COLUMN version INT NOT NULL DEFAULT 0;
ALTER TABLE payroll_periods            ADD COLUMN version INT NOT NULL DEFAULT 0;

/* ---- 5.5 employee codes: EMP-0001, EMP-0002, ... handed out by the database -
   A counter row locked inside the trigger keeps concurrent inserts from ever
   getting the same code. */
CREATE TABLE code_sequences (
  name       VARCHAR(20) PRIMARY KEY,
  next_value INT NOT NULL
) ENGINE=InnoDB;

INSERT INTO code_sequences (name, next_value)
SELECT 'EMP', COALESCE(MAX(emp_id), 0) + 1 FROM employees;

DELIMITER $$
CREATE TRIGGER trg_employees_code
BEFORE INSERT ON employees
FOR EACH ROW
BEGIN
  DECLARE v_next INT;
  IF NEW.emp_code IS NULL OR NEW.emp_code = '' THEN
    SELECT next_value INTO v_next FROM code_sequences WHERE name = 'EMP' FOR UPDATE;
    UPDATE code_sequences SET next_value = v_next + 1 WHERE name = 'EMP';
    SET NEW.emp_code = CONCAT('EMP-', LPAD(v_next, 4, '0'));
  END IF;
END$$
DELIMITER ;

/* ---- 10.5 renewal no longer loses the contract's original end date ---- */
ALTER TABLE employee_contracts ADD COLUMN original_end_date DATE NULL AFTER end_date;

/* ---- 10.3 leave rules --------------------------------------------------- */
-- supporting document reference (file number, link, ...) for leave types with requires_attachment = 1
ALTER TABLE leave_requests ADD COLUMN attachment_ref VARCHAR(255) NULL AFTER reason;

CREATE TABLE public_holidays (
  holiday_date DATE PRIMARY KEY,
  name_en      VARCHAR(80) NOT NULL,
  name_ar      VARCHAR(80) NOT NULL
) ENGINE=InnoDB;

-- fixed-date Egyptian public holidays for 2025-2026; moving (lunar) holidays are added by HR each year
INSERT INTO public_holidays (holiday_date, name_en, name_ar) VALUES
 ('2025-01-07','Coptic Christmas',        'عيد الميلاد المجيد'),
 ('2025-01-25','Revolution Day (Jan 25)', 'عيد ثورة 25 يناير'),
 ('2025-04-25','Sinai Liberation Day',    'عيد تحرير سيناء'),
 ('2025-05-01','Labour Day',              'عيد العمال'),
 ('2025-06-30','June 30 Revolution',      'ذكرى ثورة 30 يونيو'),
 ('2025-07-23','Revolution Day (Jul 23)', 'عيد ثورة 23 يوليو'),
 ('2025-10-06','Armed Forces Day',        'عيد القوات المسلحة'),
 ('2026-01-07','Coptic Christmas',        'عيد الميلاد المجيد'),
 ('2026-01-25','Revolution Day (Jan 25)', 'عيد ثورة 25 يناير'),
 ('2026-04-25','Sinai Liberation Day',    'عيد تحرير سيناء'),
 ('2026-05-01','Labour Day',              'عيد العمال'),
 ('2026-06-30','June 30 Revolution',      'ذكرى ثورة 30 يونيو'),
 ('2026-07-23','Revolution Day (Jul 23)', 'عيد ثورة 23 يوليو'),
 ('2026-10-06','Armed Forces Day',        'عيد القوات المسلحة');

/* ---- 9.9 audit trail ---------------------------------------------------- */
CREATE TABLE audit_log (
  audit_id     BIGINT AUTO_INCREMENT PRIMARY KEY,
  occurred_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actor        VARCHAR(50) NOT NULL,
  action       VARCHAR(40) NOT NULL,
  target_type  VARCHAR(40) NOT NULL,
  target_id    VARCHAR(40) NOT NULL,
  details      VARCHAR(500),
  INDEX idx_audit_target (target_type, target_id),
  INDEX idx_audit_time (occurred_at)
) ENGINE=InnoDB;

/* ---- 9.5 refresh tokens + disabling users -------------------------------- */
ALTER TABLE hr_users ADD COLUMN enabled TINYINT(1) NOT NULL DEFAULT 1;

CREATE TABLE refresh_tokens (
  token_id    BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id     INT NOT NULL,
  token_hash  CHAR(64) NOT NULL UNIQUE,      -- SHA-256 of the cookie value; the raw token is never stored
  expires_at  DATETIME NOT NULL,
  revoked_at  DATETIME NULL,
  created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_refresh_user FOREIGN KEY (user_id) REFERENCES hr_users(user_id) ON DELETE CASCADE,
  INDEX idx_refresh_user (user_id)
) ENGINE=InnoDB;

/* ---- performance: headcount view joined to active contracts ---------------
   Replaces one fn_current_basic() lookup per employee inside AVG(). */
CREATE OR REPLACE VIEW v_headcount_by_dept AS
SELECT d.code, d.name_ar AS department, b.name_ar AS branch,
       COUNT(e.emp_id) AS headcount,
       SUM(e.gender = 'M') AS males, SUM(e.gender = 'F') AS females,
       ROUND(AVG(TIMESTAMPDIFF(YEAR, e.hire_date, CURDATE())),1) AS avg_service_years,
       ROUND(AVG(IFNULL(c.basic_salary, 0)),2) AS avg_basic_salary
FROM departments d
JOIN branches b ON b.branch_id = d.branch_id
LEFT JOIN employees e ON e.dept_id = d.dept_id AND e.emp_status IN ('ACTIVE','PROBATION')
LEFT JOIN (SELECT emp_id, basic_salary,
                  ROW_NUMBER() OVER (PARTITION BY emp_id ORDER BY start_date DESC) AS rn
             FROM employee_contracts
            WHERE status = 'ACTIVE' AND start_date <= CURDATE()
              AND (end_date IS NULL OR end_date >= CURDATE())) c
       ON c.emp_id = e.emp_id AND c.rn = 1
GROUP BY d.code, d.name_ar, b.name_ar;
