spring.application.name=erphrapp

# connect to the database
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/erp_hr?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=REMOVED

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# set up for JWT authentication
jwt.secret=REMOVED
jwt.expiration=28800000 

# expiration is 28800000ms which is 8 hours
# secret key is used in verifying authentication token