/* =====================================================================
   ERP  --  Human Resources & Payroll Module   (Hypothetical Company)
   Company : Nile Industrial Group  /  مجموعة النيل الصناعية
   Engine  : MySQL 8.0+ / 9.x   |  Charset: utf8mb4   |  Currency: EGP
   ---------------------------------------------------------------------
   Contents
     01. Database & organisation structure
     02. Employees, contracts & bank data
     03. Salary structure (components, tax brackets, settings)
     04. Attendance & leave management
     05. Loans / advances
     06. Payroll periods, payslips & payment register
     07. Functions, procedures & triggers (payroll engine)
     08. Reporting views
     09. Seed data
     10. Payroll runs (generated by the engine)
   ===================================================================== */

DROP DATABASE IF EXISTS erp_hr;
CREATE DATABASE erp_hr CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE erp_hr;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 1;

/* =====================================================================
   01. ORGANISATION STRUCTURE
   ===================================================================== */

CREATE TABLE branches (
                          branch_id     INT AUTO_INCREMENT PRIMARY KEY,
                          code          VARCHAR(10)  NOT NULL UNIQUE,
                          name_en       VARCHAR(80)  NOT NULL,
                          name_ar       VARCHAR(80)  NOT NULL,
                          city          VARCHAR(50)  NOT NULL,
                          country       VARCHAR(50)  NOT NULL DEFAULT 'Egypt',
                          address       VARCHAR(200),
                          is_active     TINYINT(1)   NOT NULL DEFAULT 1
) ENGINE=InnoDB;

CREATE TABLE departments (
                             dept_id        INT AUTO_INCREMENT PRIMARY KEY,
                             code           VARCHAR(10) NOT NULL UNIQUE,
                             name_en        VARCHAR(80) NOT NULL,
                             name_ar        VARCHAR(80) NOT NULL,
                             parent_dept_id INT NULL,
                             cost_center    VARCHAR(20) NOT NULL,
                             branch_id      INT NOT NULL,
                             is_active      TINYINT(1)  NOT NULL DEFAULT 1,
                             CONSTRAINT fk_dept_parent FOREIGN KEY (parent_dept_id) REFERENCES departments(dept_id),
                             CONSTRAINT fk_dept_branch FOREIGN KEY (branch_id)      REFERENCES branches(branch_id)
) ENGINE=InnoDB;

CREATE TABLE job_titles (
                            job_id      INT AUTO_INCREMENT PRIMARY KEY,
                            code        VARCHAR(12) NOT NULL UNIQUE,
                            title_en    VARCHAR(80) NOT NULL,
                            title_ar    VARCHAR(80) NOT NULL,
                            job_grade   ENUM('G1','G2','G3','G4','G5','G6','G7') NOT NULL,
                            min_salary  DECIMAL(12,2) NOT NULL,
                            max_salary  DECIMAL(12,2) NOT NULL,
                            is_managerial TINYINT(1) NOT NULL DEFAULT 0,
                            CONSTRAINT chk_job_range CHECK (max_salary >= min_salary)
) ENGINE=InnoDB;


/* =====================================================================
   02. EMPLOYEES
   ===================================================================== */

CREATE TABLE hr_users (
                          user_id   INT AUTO_INCREMENT PRIMARY KEY,
                          username  VARCHAR(50) NOT NULL UNIQUE,
                          password  VARCHAR(255) NOT NULL,
                          role      ENUM('HR_ADMIN','HR_USER') NOT NULL
) ENGINE=InnoDB;

-- Seed admin: replace the hash below with one generated via BCryptPasswordEncoder
-- before running this script — do not commit a real password hash to git.
INSERT INTO hr_users (username, password, role)
VALUES ('admin', '${ADMIN_PASSWORD_HASH}', 'HR_ADMIN');

CREATE TABLE employees (
                           emp_id          INT AUTO_INCREMENT PRIMARY KEY,
                           emp_code        VARCHAR(12) NOT NULL UNIQUE,
                           full_name_ar    VARCHAR(120) NOT NULL,
                           full_name_en    VARCHAR(120) NOT NULL,
                           gender          ENUM('M','F') NOT NULL,
                           birth_date      DATE NOT NULL,
                           national_id     CHAR(14) NOT NULL UNIQUE,
                           marital_status  ENUM('SINGLE','MARRIED','DIVORCED','WIDOWED') NOT NULL DEFAULT 'SINGLE',
                           dependents      TINYINT NOT NULL DEFAULT 0,
                           email           VARCHAR(100) UNIQUE,
                           mobile          VARCHAR(20),
                           address         VARCHAR(200),
                           hire_date       DATE NOT NULL,
                           dept_id         INT NOT NULL,
                           job_id          INT NOT NULL,
                           branch_id       INT NOT NULL,
                           manager_id      INT NULL,
                           emp_status      ENUM('ACTIVE','PROBATION','SUSPENDED','RESIGNED','TERMINATED') NOT NULL DEFAULT 'ACTIVE',
                           termination_date DATE NULL,
                           insurance_no    VARCHAR(20) UNIQUE,
                           bank_name       VARCHAR(60),
                           bank_account    VARCHAR(34),
                           payment_method  ENUM('BANK','CASH','CHEQUE') NOT NULL DEFAULT 'BANK',
                           created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                           updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                           CONSTRAINT fk_emp_dept    FOREIGN KEY (dept_id)    REFERENCES departments(dept_id),
                           CONSTRAINT fk_emp_job     FOREIGN KEY (job_id)     REFERENCES job_titles(job_id),
                           CONSTRAINT fk_emp_branch  FOREIGN KEY (branch_id)  REFERENCES branches(branch_id),
                           CONSTRAINT fk_emp_manager FOREIGN KEY (manager_id) REFERENCES employees(emp_id),
                           CONSTRAINT chk_term CHECK (termination_date IS NULL OR termination_date >= hire_date),
                           INDEX idx_emp_dept (dept_id),
                           INDEX idx_emp_status (emp_status),
                           INDEX idx_emp_hire (hire_date)
) ENGINE=InnoDB;

CREATE TABLE employee_contracts (
                                    contract_id    INT AUTO_INCREMENT PRIMARY KEY,
                                    emp_id         INT NOT NULL,
                                    contract_no    VARCHAR(20) NOT NULL UNIQUE,
                                    contract_type  ENUM('PERMANENT','FIXED_TERM','PART_TIME','CONSULTANT','INTERN') NOT NULL,
                                    start_date     DATE NOT NULL,
                                    end_date       DATE NULL,
                                    basic_salary   DECIMAL(12,2) NOT NULL,
                                    currency       CHAR(3) NOT NULL DEFAULT 'EGP',
                                    weekly_hours   DECIMAL(4,1) NOT NULL DEFAULT 40.0,
                                    annual_leave_days SMALLINT NOT NULL DEFAULT 21,
                                    probation_months TINYINT NOT NULL DEFAULT 3,
                                    status         ENUM('ACTIVE','EXPIRED','TERMINATED') NOT NULL DEFAULT 'ACTIVE',
                                    notes          VARCHAR(255),
                                    CONSTRAINT fk_contract_emp FOREIGN KEY (emp_id) REFERENCES employees(emp_id) ON DELETE CASCADE,
                                    CONSTRAINT chk_contract_dates CHECK (end_date IS NULL OR end_date > start_date),
                                    CONSTRAINT chk_basic_positive CHECK (basic_salary > 0),
                                    INDEX idx_contract_emp (emp_id, status)
) ENGINE=InnoDB;

/* =====================================================================
   03. SALARY STRUCTURE
   ===================================================================== */

CREATE TABLE payroll_settings (
                                  fiscal_year         SMALLINT PRIMARY KEY,
                                  personal_exemption  DECIMAL(12,2) NOT NULL,   -- annual, income-tax exemption
                                  ins_min_wage        DECIMAL(12,2) NOT NULL,   -- social insurance floor  (monthly)
                                  ins_max_wage        DECIMAL(12,2) NOT NULL,   -- social insurance ceiling(monthly)
                                  ins_employee_rate   DECIMAL(5,2)  NOT NULL,   -- %
                                  ins_employer_rate   DECIMAL(5,2)  NOT NULL,   -- %
                                  working_days_month  TINYINT       NOT NULL DEFAULT 30,
                                  daily_hours         DECIMAL(4,1)  NOT NULL DEFAULT 8.0,
                                  overtime_factor     DECIMAL(4,2)  NOT NULL DEFAULT 1.50
) ENGINE=InnoDB;

CREATE TABLE tax_brackets (
                              bracket_id  INT AUTO_INCREMENT PRIMARY KEY,
                              fiscal_year SMALLINT NOT NULL,
                              from_amount DECIMAL(14,2) NOT NULL,           -- annual taxable income
                              to_amount   DECIMAL(14,2) NOT NULL,
                              rate        DECIMAL(5,2)  NOT NULL,           -- %
                              CONSTRAINT fk_bracket_year FOREIGN KEY (fiscal_year) REFERENCES payroll_settings(fiscal_year),
                              UNIQUE KEY uq_bracket (fiscal_year, from_amount)
) ENGINE=InnoDB;

CREATE TABLE salary_components (
                                   comp_id        INT AUTO_INCREMENT PRIMARY KEY,
                                   code           VARCHAR(12) NOT NULL UNIQUE,
                                   name_en        VARCHAR(60) NOT NULL,
                                   name_ar        VARCHAR(60) NOT NULL,
                                   comp_type      ENUM('EARNING','DEDUCTION') NOT NULL,
                                   calc_type      ENUM('FIXED','PCT_BASIC','COMPUTED') NOT NULL,
                                   default_value  DECIMAL(12,2) NOT NULL DEFAULT 0,   -- amount, or % when PCT_BASIC
                                   is_taxable     TINYINT(1) NOT NULL DEFAULT 1,
                                   is_insurable   TINYINT(1) NOT NULL DEFAULT 0,
                                   is_recurring   TINYINT(1) NOT NULL DEFAULT 1,
                                   print_order    SMALLINT NOT NULL DEFAULT 100,
                                   is_active      TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB;

CREATE TABLE employee_salary_components (
                                            id             INT AUTO_INCREMENT PRIMARY KEY,
                                            emp_id         INT NOT NULL,
                                            comp_id        INT NOT NULL,
                                            amount         DECIMAL(12,2) NULL,   -- overrides default (FIXED)
                                            percentage     DECIMAL(5,2)  NULL,   -- overrides default (PCT_BASIC)
                                            effective_from DATE NOT NULL,
                                            effective_to   DATE NULL,
                                            notes          VARCHAR(150),
                                            CONSTRAINT fk_esc_emp  FOREIGN KEY (emp_id)  REFERENCES employees(emp_id) ON DELETE CASCADE,
                                            CONSTRAINT fk_esc_comp FOREIGN KEY (comp_id) REFERENCES salary_components(comp_id),
                                            UNIQUE KEY uq_esc (emp_id, comp_id, effective_from),
                                            INDEX idx_esc_lookup (emp_id, effective_from, effective_to)
) ENGINE=InnoDB;

/* =====================================================================
   04. LEAVES & ATTENDANCE
   ===================================================================== */

CREATE TABLE leave_types (
                             type_id        INT AUTO_INCREMENT PRIMARY KEY,
                             code           VARCHAR(10) NOT NULL UNIQUE,
                             name_en        VARCHAR(60) NOT NULL,
                             name_ar        VARCHAR(60) NOT NULL,
                             annual_quota   SMALLINT NOT NULL DEFAULT 0,
                             is_paid        TINYINT(1) NOT NULL DEFAULT 1,
                             affects_balance TINYINT(1) NOT NULL DEFAULT 1,
                             max_consecutive SMALLINT NOT NULL DEFAULT 30,
                             requires_attachment TINYINT(1) NOT NULL DEFAULT 0,
                             gender_restriction ENUM('ANY','M','F') NOT NULL DEFAULT 'ANY'
) ENGINE=InnoDB;

CREATE TABLE leave_balances (
                                balance_id      INT AUTO_INCREMENT PRIMARY KEY,
                                emp_id          INT NOT NULL,
                                type_id         INT NOT NULL,
                                fiscal_year     SMALLINT NOT NULL,
                                entitled_days   DECIMAL(5,1) NOT NULL DEFAULT 0,
                                carried_forward DECIMAL(5,1) NOT NULL DEFAULT 0,
                                used_days       DECIMAL(5,1) NOT NULL DEFAULT 0,
                                remaining_days  DECIMAL(5,1) AS (entitled_days + carried_forward - used_days) STORED,
                                CONSTRAINT fk_bal_emp  FOREIGN KEY (emp_id)  REFERENCES employees(emp_id) ON DELETE CASCADE,
                                CONSTRAINT fk_bal_type FOREIGN KEY (type_id) REFERENCES leave_types(type_id),
                                UNIQUE KEY uq_balance (emp_id, type_id, fiscal_year)
) ENGINE=InnoDB;

CREATE TABLE leave_requests (
                                request_id   INT AUTO_INCREMENT PRIMARY KEY,
                                emp_id       INT NOT NULL,
                                type_id      INT NOT NULL,
                                start_date   DATE NOT NULL,
                                end_date     DATE NOT NULL,
                                days_count   DECIMAL(4,1) NOT NULL,
                                reason       VARCHAR(200),
                                status       ENUM('PENDING','APPROVED','REJECTED','CANCELLED') NOT NULL DEFAULT 'PENDING',
                                applied_on   DATE NOT NULL,
                                approver_id  INT NULL,
                                decided_on   DATE NULL,
                                reject_reason VARCHAR(200),
                                CONSTRAINT fk_lr_emp      FOREIGN KEY (emp_id)      REFERENCES employees(emp_id) ON DELETE CASCADE,
                                CONSTRAINT fk_lr_type     FOREIGN KEY (type_id)     REFERENCES leave_types(type_id),
                                CONSTRAINT fk_lr_approver FOREIGN KEY (approver_id) REFERENCES employees(emp_id),
                                CONSTRAINT chk_lr_dates CHECK (end_date >= start_date),
                                INDEX idx_lr_emp (emp_id, status),
                                INDEX idx_lr_period (start_date, end_date)
) ENGINE=InnoDB;

/* =====================================================================
   05. LOANS / SALARY ADVANCES
   ===================================================================== */

CREATE TABLE loans (
                       loan_id            INT AUTO_INCREMENT PRIMARY KEY,
                       emp_id             INT NOT NULL,
                       loan_type          ENUM('ADVANCE','PERSONAL','EMERGENCY','HOUSING') NOT NULL,
                       principal_amount   DECIMAL(12,2) NOT NULL,
                       installments_count SMALLINT NOT NULL,
                       monthly_installment DECIMAL(12,2) NOT NULL,
                       remaining_balance  DECIMAL(12,2) NOT NULL,
                       start_period       CHAR(7) NOT NULL,          -- YYYY-MM
                       approved_by        INT NULL,
                       status             ENUM('ACTIVE','CLOSED','CANCELLED') NOT NULL DEFAULT 'ACTIVE',
                       request_date       DATE NOT NULL,
                       CONSTRAINT fk_loan_emp FOREIGN KEY (emp_id) REFERENCES employees(emp_id) ON DELETE CASCADE,
                       CONSTRAINT fk_loan_appr FOREIGN KEY (approved_by) REFERENCES employees(emp_id),
                       CONSTRAINT chk_loan_amt CHECK (principal_amount > 0 AND monthly_installment > 0),
                       INDEX idx_loan_emp (emp_id, status)
) ENGINE=InnoDB;

/* =====================================================================
   06. PAYROLL PERIODS, PAYSLIPS & PAYMENTS
   ===================================================================== */

CREATE TABLE payroll_periods (
                                 period_id    INT AUTO_INCREMENT PRIMARY KEY,
                                 period_code  CHAR(7) NOT NULL UNIQUE,          -- 2026-07
                                 fiscal_year  SMALLINT NOT NULL,
                                 start_date   DATE NOT NULL,
                                 end_date     DATE NOT NULL,
                                 pay_date     DATE NOT NULL,
                                 working_days TINYINT NOT NULL DEFAULT 22,
                                 status       ENUM('OPEN','PROCESSED','APPROVED','PAID','CLOSED') NOT NULL DEFAULT 'OPEN',
                                 processed_at DATETIME NULL,
                                 approved_by  INT NULL,
                                 CONSTRAINT chk_period_dates CHECK (end_date > start_date)
) ENGINE=InnoDB;

CREATE TABLE attendance_summary (
                                    att_id            INT AUTO_INCREMENT PRIMARY KEY,
                                    period_id         INT NOT NULL,
                                    emp_id            INT NOT NULL,
                                    working_days      DECIMAL(4,1) NOT NULL,
                                    present_days      DECIMAL(4,1) NOT NULL,
                                    paid_leave_days   DECIMAL(4,1) NOT NULL DEFAULT 0,
                                    unpaid_absent_days DECIMAL(4,1) NOT NULL DEFAULT 0,
                                    overtime_hours    DECIMAL(6,2) NOT NULL DEFAULT 0,
                                    late_minutes      SMALLINT NOT NULL DEFAULT 0,
                                    CONSTRAINT fk_att_period FOREIGN KEY (period_id) REFERENCES payroll_periods(period_id) ON DELETE CASCADE,
                                    CONSTRAINT fk_att_emp    FOREIGN KEY (emp_id)    REFERENCES employees(emp_id) ON DELETE CASCADE,
                                    UNIQUE KEY uq_att (period_id, emp_id)
) ENGINE=InnoDB;

CREATE TABLE payslips (
                          payslip_id        BIGINT AUTO_INCREMENT PRIMARY KEY,
                          payslip_no        VARCHAR(24) NOT NULL UNIQUE,
                          period_id         INT NOT NULL,
                          emp_id            INT NOT NULL,
                          basic_salary      DECIMAL(12,2) NOT NULL DEFAULT 0,
                          total_earnings    DECIMAL(12,2) NOT NULL DEFAULT 0,   -- gross
                          total_deductions  DECIMAL(12,2) NOT NULL DEFAULT 0,
                          taxable_income    DECIMAL(12,2) NOT NULL DEFAULT 0,
                          income_tax        DECIMAL(12,2) NOT NULL DEFAULT 0,
                          insurance_employee DECIMAL(12,2) NOT NULL DEFAULT 0,
                          insurance_employer DECIMAL(12,2) NOT NULL DEFAULT 0,
                          net_pay           DECIMAL(12,2) NOT NULL DEFAULT 0,
                          worked_days       DECIMAL(4,1) NOT NULL DEFAULT 0,
                          absent_days       DECIMAL(4,1) NOT NULL DEFAULT 0,
                          overtime_hours    DECIMAL(6,2) NOT NULL DEFAULT 0,
                          currency          CHAR(3) NOT NULL DEFAULT 'EGP',
                          status            ENUM('DRAFT','APPROVED','PAID','CANCELLED') NOT NULL DEFAULT 'DRAFT',
                          generated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          CONSTRAINT fk_ps_period FOREIGN KEY (period_id) REFERENCES payroll_periods(period_id) ON DELETE CASCADE,
                          CONSTRAINT fk_ps_emp    FOREIGN KEY (emp_id)    REFERENCES employees(emp_id),
                          UNIQUE KEY uq_payslip (period_id, emp_id),
                          INDEX idx_ps_emp (emp_id)
) ENGINE=InnoDB;

CREATE TABLE payslip_lines (
                               line_id     BIGINT AUTO_INCREMENT PRIMARY KEY,
                               payslip_id  BIGINT NOT NULL,
                               comp_id     INT NOT NULL,
                               comp_code   VARCHAR(12) NOT NULL,
                               comp_name_ar VARCHAR(60) NOT NULL,
                               comp_type   ENUM('EARNING','DEDUCTION') NOT NULL,
                               amount      DECIMAL(12,2) NOT NULL,
                               is_taxable  TINYINT(1) NOT NULL DEFAULT 1,
                               calc_note   VARCHAR(120),
                               print_order SMALLINT NOT NULL DEFAULT 100,
                               CONSTRAINT fk_pl_payslip FOREIGN KEY (payslip_id) REFERENCES payslips(payslip_id) ON DELETE CASCADE,
                               CONSTRAINT fk_pl_comp    FOREIGN KEY (comp_id)    REFERENCES salary_components(comp_id),
                               INDEX idx_pl_payslip (payslip_id, comp_type)
) ENGINE=InnoDB;

CREATE TABLE loan_installments (
                                   inst_id    INT AUTO_INCREMENT PRIMARY KEY,
                                   loan_id    INT NOT NULL,
                                   payslip_id BIGINT NULL,
                                   period_code CHAR(7) NOT NULL,
                                   amount     DECIMAL(12,2) NOT NULL,
                                   paid_on    DATE NULL,
                                   CONSTRAINT fk_inst_loan    FOREIGN KEY (loan_id)    REFERENCES loans(loan_id) ON DELETE CASCADE,
                                   CONSTRAINT fk_inst_payslip FOREIGN KEY (payslip_id) REFERENCES payslips(payslip_id) ON DELETE SET NULL,
                                   UNIQUE KEY uq_inst (loan_id, period_code)
) ENGINE=InnoDB;

CREATE TABLE payroll_payments (
                                  payment_id  BIGINT AUTO_INCREMENT PRIMARY KEY,
                                  payslip_id  BIGINT NOT NULL,
                                  method      ENUM('BANK','CASH','CHEQUE') NOT NULL,
                                  bank_name   VARCHAR(60),
                                  bank_account VARCHAR(34),
                                  amount      DECIMAL(12,2) NOT NULL,
                                  paid_on     DATE NOT NULL,
                                  reference   VARCHAR(40),
                                  CONSTRAINT fk_pay_payslip FOREIGN KEY (payslip_id) REFERENCES payslips(payslip_id) ON DELETE CASCADE,
                                  UNIQUE KEY uq_payment (payslip_id)
) ENGINE=InnoDB;

/* =====================================================================
   07. PAYROLL ENGINE  (functions, procedures, triggers)
   ===================================================================== */

DELIMITER $$

/* ---- Progressive income tax on annualised taxable income ---------- */
CREATE FUNCTION fn_income_tax(p_monthly_taxable DECIMAL(12,2), p_year SMALLINT)
    RETURNS DECIMAL(12,2)
    READS SQL DATA
BEGIN
  DECLARE v_annual   DECIMAL(14,2);
  DECLARE v_exempt   DECIMAL(14,2);
  DECLARE v_tax      DECIMAL(14,2);

SELECT personal_exemption INTO v_exempt FROM payroll_settings WHERE fiscal_year = p_year;
SET v_annual = GREATEST(0, (p_monthly_taxable * 12) - IFNULL(v_exempt, 0));

SELECT IFNULL(SUM(GREATEST(0, LEAST(v_annual, to_amount) - from_amount) * rate / 100), 0)
INTO v_tax
FROM tax_brackets
WHERE fiscal_year = p_year;

RETURN ROUND(v_tax / 12, 2);
END$$

/* ---- Social-insurance wage (floor / ceiling applied) --------------- */
CREATE FUNCTION fn_insurance_wage(p_basic DECIMAL(12,2), p_year SMALLINT)
    RETURNS DECIMAL(12,2)
    READS SQL DATA
BEGIN
  DECLARE v_min DECIMAL(12,2);
  DECLARE v_max DECIMAL(12,2);
SELECT ins_min_wage, ins_max_wage INTO v_min, v_max
FROM payroll_settings WHERE fiscal_year = p_year;
RETURN LEAST(GREATEST(p_basic, v_min), v_max);
END$$

/* ---- Current basic salary of an employee at a given date ---------- */
CREATE FUNCTION fn_current_basic(p_emp INT, p_date DATE)
    RETURNS DECIMAL(12,2)
    READS SQL DATA
BEGIN
  DECLARE v_basic DECIMAL(12,2);
SELECT basic_salary INTO v_basic
FROM employee_contracts
WHERE emp_id = p_emp
  AND start_date <= p_date
  AND (end_date IS NULL OR end_date >= p_date)
  AND status = 'ACTIVE'
ORDER BY start_date DESC LIMIT 1;
RETURN IFNULL(v_basic, 0);
END$$

/* =====================================================================
   sp_run_payroll : generates payslips + payslip lines for one period
   --------------------------------------------------------------------
   Order of calculation
     1. basic salary (pro-rated for mid-month hires)
     2. recurring earnings  (fixed / % of basic)
     3. overtime            (basic / days / hours * factor)
     4. gross               = SUM(earnings)
     5. social insurance    (employee 11% / employer 18.75% of ins. wage)
     6. income tax          (progressive, on taxable earnings - insurance)
     7. absence deduction, loan installment, recurring deductions
     8. net pay             = gross - SUM(deductions)
   ===================================================================== */
CREATE PROCEDURE sp_run_payroll(IN p_period_code CHAR(7))
BEGIN
  DECLARE v_period_id  INT;
  DECLARE v_year       SMALLINT;
  DECLARE v_start      DATE;
  DECLARE v_end        DATE;
  DECLARE v_wdays      TINYINT;
  DECLARE v_dhours     DECIMAL(4,1);
  DECLARE v_ot_factor  DECIMAL(4,2);
  DECLARE v_r_emp      DECIMAL(5,2);
  DECLARE v_r_er       DECIMAL(5,2);

  DECLARE v_emp        INT;
  DECLARE v_hire       DATE;
  DECLARE v_basic      DECIMAL(12,2);
  DECLARE v_prorate    DECIMAL(6,4);
  DECLARE v_payslip    BIGINT;
  DECLARE v_gross      DECIMAL(12,2);
  DECLARE v_taxable    DECIMAL(12,2);
  DECLARE v_ins_wage   DECIMAL(12,2);
  DECLARE v_ins_emp    DECIMAL(12,2);
  DECLARE v_ins_er     DECIMAL(12,2);
  DECLARE v_tax        DECIMAL(12,2);
  DECLARE v_ot_hours   DECIMAL(6,2);
  DECLARE v_ot_amount  DECIMAL(12,2);
  DECLARE v_abs_days   DECIMAL(4,1);
  DECLARE v_abs_amount DECIMAL(12,2);
  DECLARE v_present    DECIMAL(4,1);
  DECLARE v_loan_id    INT;
  DECLARE v_loan_inst  DECIMAL(12,2);
  DECLARE v_done       INT DEFAULT 0;

  DECLARE cur_emp CURSOR FOR
SELECT e.emp_id, e.hire_date
FROM employees e
WHERE (e.emp_status IN ('ACTIVE','PROBATION','SUSPENDED')
    OR e.termination_date IS NOT NULL)
  AND e.hire_date <= v_end
  AND (e.termination_date IS NULL OR e.termination_date >= v_start)
ORDER BY e.emp_id;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET v_done = 1;

SELECT period_id, fiscal_year, start_date, end_date, working_days
INTO v_period_id, v_year, v_start, v_end, v_wdays
FROM payroll_periods WHERE period_code = p_period_code;

IF v_period_id IS NULL THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Payroll period not found';
END IF;

SELECT daily_hours, overtime_factor, ins_employee_rate, ins_employer_rate
INTO v_dhours, v_ot_factor, v_r_emp, v_r_er
FROM payroll_settings WHERE fiscal_year = v_year;

/* re-run safe: roll back loan installments, then wipe the old run */
UPDATE loans l
    JOIN loan_installments li ON li.loan_id = l.loan_id AND li.period_code = p_period_code
    SET l.remaining_balance = l.remaining_balance + li.amount,
        l.status = 'ACTIVE';
DELETE FROM loan_installments WHERE period_code = p_period_code;
DELETE FROM payslips WHERE period_id = v_period_id;

OPEN cur_emp;
emp_loop: LOOP
    FETCH cur_emp INTO v_emp, v_hire;
    IF v_done = 1 THEN LEAVE emp_loop; END IF;

    SET v_basic = fn_current_basic(v_emp, v_end);
    IF v_basic <= 0 THEN ITERATE emp_loop; END IF;

    /* pro-rate the month for employees hired mid-period */
    SET v_prorate = IF(v_hire > v_start,
                       (DATEDIFF(v_end, v_hire) + 1) / (DATEDIFF(v_end, v_start) + 1), 1.0000);

SELECT IFNULL(overtime_hours,0), IFNULL(unpaid_absent_days,0), IFNULL(present_days,0)
INTO v_ot_hours, v_abs_days, v_present
FROM attendance_summary WHERE period_id = v_period_id AND emp_id = v_emp;
IF v_done = 1 THEN
      SET v_ot_hours = 0, v_abs_days = 0, v_present = v_wdays, v_done = 0;
END IF;

INSERT INTO payslips (payslip_no, period_id, emp_id, basic_salary,
                      worked_days, absent_days, overtime_hours, status)
VALUES (CONCAT('PS-', REPLACE(p_period_code,'-',''), '-', LPAD(v_emp,4,'0')),
        v_period_id, v_emp, ROUND(v_basic * v_prorate, 2),
        v_present, v_abs_days, v_ot_hours, 'DRAFT');
SET v_payslip = LAST_INSERT_ID();

    /* -------- 1. basic ------------------------------------------- */
INSERT INTO payslip_lines (payslip_id, comp_id, comp_code, comp_name_ar, comp_type,
                           amount, is_taxable, calc_note, print_order)
SELECT v_payslip, comp_id, code, name_ar, 'EARNING',
       ROUND(v_basic * v_prorate, 2), is_taxable,
       IF(v_prorate < 1, CONCAT('Pro-rated ', ROUND(v_prorate*100,1), '%'), 'Full month'), print_order
FROM salary_components WHERE code = 'BASIC';

/* -------- 2. recurring earnings ------------------------------ */
INSERT INTO payslip_lines (payslip_id, comp_id, comp_code, comp_name_ar, comp_type,
                           amount, is_taxable, calc_note, print_order)
SELECT v_payslip, sc.comp_id, sc.code, sc.name_ar, 'EARNING',
       ROUND(CASE sc.calc_type
                 WHEN 'PCT_BASIC' THEN v_basic * IFNULL(esc.percentage, sc.default_value) / 100
                 ELSE IFNULL(esc.amount, sc.default_value)
                 END * v_prorate, 2),
       sc.is_taxable,
       CASE sc.calc_type
           WHEN 'PCT_BASIC' THEN CONCAT(IFNULL(esc.percentage, sc.default_value), '% of basic')
           ELSE 'Fixed amount' END,
       sc.print_order
FROM employee_salary_components esc
         JOIN salary_components sc ON sc.comp_id = esc.comp_id
WHERE esc.emp_id = v_emp
  AND sc.comp_type = 'EARNING'
  AND sc.calc_type <> 'COMPUTED'
  AND sc.is_active = 1
  AND esc.effective_from <= v_end
  AND (esc.effective_to IS NULL OR esc.effective_to >= v_start);

/* -------- 3. overtime ---------------------------------------- */
IF v_ot_hours > 0 THEN
      SET v_ot_amount = ROUND((v_basic / v_wdays / v_dhours) * v_ot_factor * v_ot_hours, 2);
INSERT INTO payslip_lines (payslip_id, comp_id, comp_code, comp_name_ar, comp_type,
                           amount, is_taxable, calc_note, print_order)
SELECT v_payslip, comp_id, code, name_ar, 'EARNING', v_ot_amount, is_taxable,
       CONCAT(v_ot_hours, ' hrs x ', v_ot_factor), print_order
FROM salary_components WHERE code = 'OT';
END IF;

    /* -------- 4. gross & taxable base ---------------------------- */
SELECT IFNULL(SUM(amount),0), IFNULL(SUM(IF(is_taxable = 1, amount, 0)),0)
INTO v_gross, v_taxable
FROM payslip_lines WHERE payslip_id = v_payslip AND comp_type = 'EARNING';

/* -------- 5. social insurance -------------------------------- */
SET v_ins_wage = fn_insurance_wage(v_basic, v_year);
    SET v_ins_emp  = ROUND(v_ins_wage * v_r_emp / 100, 2);
    SET v_ins_er   = ROUND(v_ins_wage * v_r_er  / 100, 2);

INSERT INTO payslip_lines (payslip_id, comp_id, comp_code, comp_name_ar, comp_type,
                           amount, is_taxable, calc_note, print_order)
SELECT v_payslip, comp_id, code, name_ar, 'DEDUCTION', v_ins_emp, 0,
       CONCAT(v_r_emp, '% of ', v_ins_wage), print_order
FROM salary_components WHERE code = 'INS';

/* -------- 6. income tax -------------------------------------- */
SET v_taxable = GREATEST(0, v_taxable - v_ins_emp);
    SET v_tax = fn_income_tax(v_taxable, v_year);

    IF v_tax > 0 THEN
      INSERT INTO payslip_lines (payslip_id, comp_id, comp_code, comp_name_ar, comp_type,
                                 amount, is_taxable, calc_note, print_order)
SELECT v_payslip, comp_id, code, name_ar, 'DEDUCTION', v_tax, 0,
       CONCAT('Progressive on ', v_taxable), print_order
FROM salary_components WHERE code = 'TAX';
END IF;

    /* -------- 7a. unpaid absence --------------------------------- */
    IF v_abs_days > 0 THEN
      SET v_abs_amount = ROUND((v_gross / v_wdays) * v_abs_days, 2);
INSERT INTO payslip_lines (payslip_id, comp_id, comp_code, comp_name_ar, comp_type,
                           amount, is_taxable, calc_note, print_order)
SELECT v_payslip, comp_id, code, name_ar, 'DEDUCTION', v_abs_amount, 0,
       CONCAT(v_abs_days, ' unpaid day(s)'), print_order
FROM salary_components WHERE code = 'ABS';
END IF;

    /* -------- 7b. other recurring deductions --------------------- */
INSERT INTO payslip_lines (payslip_id, comp_id, comp_code, comp_name_ar, comp_type,
                           amount, is_taxable, calc_note, print_order)
SELECT v_payslip, sc.comp_id, sc.code, sc.name_ar, 'DEDUCTION',
       ROUND(CASE sc.calc_type
                 WHEN 'PCT_BASIC' THEN v_basic * IFNULL(esc.percentage, sc.default_value) / 100
                 ELSE IFNULL(esc.amount, sc.default_value) END, 2),
       0,
       CASE sc.calc_type WHEN 'PCT_BASIC' THEN 'Percentage of basic' ELSE 'Fixed amount' END,
       sc.print_order
FROM employee_salary_components esc
         JOIN salary_components sc ON sc.comp_id = esc.comp_id
WHERE esc.emp_id = v_emp
  AND sc.comp_type = 'DEDUCTION'
  AND sc.calc_type <> 'COMPUTED'
  AND sc.is_active = 1
  AND esc.effective_from <= v_end
  AND (esc.effective_to IS NULL OR esc.effective_to >= v_start);

/* -------- 7c. loan installment ------------------------------- */
SET v_loan_id = NULL;
SELECT loan_id, LEAST(monthly_installment, remaining_balance)
INTO v_loan_id, v_loan_inst
FROM loans
WHERE emp_id = v_emp AND status = 'ACTIVE'
  AND remaining_balance > 0 AND start_period <= p_period_code
ORDER BY loan_id LIMIT 1;
IF v_done = 1 THEN SET v_done = 0; SET v_loan_id = NULL; END IF;

    IF v_loan_id IS NOT NULL THEN
      INSERT INTO payslip_lines (payslip_id, comp_id, comp_code, comp_name_ar, comp_type,
                                 amount, is_taxable, calc_note, print_order)
SELECT v_payslip, comp_id, code, name_ar, 'DEDUCTION', v_loan_inst, 0,
       CONCAT('Loan #', v_loan_id), print_order
FROM salary_components WHERE code = 'LOAN';

INSERT INTO loan_installments (loan_id, payslip_id, period_code, amount)
VALUES (v_loan_id, v_payslip, p_period_code, v_loan_inst);

UPDATE loans
SET status = IF(remaining_balance - v_loan_inst <= 0, 'CLOSED', 'ACTIVE'),
    remaining_balance = remaining_balance - v_loan_inst
WHERE loan_id = v_loan_id;
END IF;

    /* -------- 8. totals ------------------------------------------ */
UPDATE payslips p
SET p.total_earnings   = (SELECT IFNULL(SUM(amount),0) FROM payslip_lines
                          WHERE payslip_id = v_payslip AND comp_type = 'EARNING'),
    p.total_deductions = (SELECT IFNULL(SUM(amount),0) FROM payslip_lines
                          WHERE payslip_id = v_payslip AND comp_type = 'DEDUCTION'),
    p.taxable_income   = v_taxable,
    p.income_tax       = v_tax,
    p.insurance_employee = v_ins_emp,
    p.insurance_employer = v_ins_er
WHERE p.payslip_id = v_payslip;

UPDATE payslips SET net_pay = total_earnings - total_deductions
WHERE payslip_id = v_payslip;

END LOOP;
CLOSE cur_emp;

UPDATE payroll_periods
SET status = 'PROCESSED', processed_at = NOW()
WHERE period_id = v_period_id;
END$$

/* ---- Approve + pay a whole period -------------------------------- */
CREATE PROCEDURE sp_pay_period(IN p_period_code CHAR(7), IN p_reference_prefix VARCHAR(10))
BEGIN
  DECLARE v_period_id INT;
  DECLARE v_pay_date  DATE;

SELECT period_id, pay_date INTO v_period_id, v_pay_date
FROM payroll_periods WHERE period_code = p_period_code;

UPDATE payslips SET status = 'PAID' WHERE period_id = v_period_id AND status <> 'CANCELLED';

INSERT INTO payroll_payments (payslip_id, method, bank_name, bank_account, amount, paid_on, reference)
SELECT p.payslip_id, e.payment_method, e.bank_name, e.bank_account, p.net_pay, v_pay_date,
       CONCAT(p_reference_prefix, '-', REPLACE(p_period_code,'-',''), '-', LPAD(e.emp_id,4,'0'))
FROM payslips p JOIN employees e ON e.emp_id = p.emp_id
WHERE p.period_id = v_period_id AND p.status = 'PAID';

UPDATE loan_installments li
    JOIN payslips p ON p.payslip_id = li.payslip_id
    SET li.paid_on = v_pay_date
WHERE p.period_id = v_period_id;

UPDATE payroll_periods SET status = 'PAID' WHERE period_id = v_period_id;
END$$

/* ---- Keep leave balances in sync with approvals ------------------- */
CREATE TRIGGER trg_leave_approved
    AFTER UPDATE ON leave_requests
    FOR EACH ROW
BEGIN
    IF NEW.status = 'APPROVED' AND OLD.status <> 'APPROVED' THEN
    UPDATE leave_balances
    SET used_days = used_days + NEW.days_count
    WHERE emp_id = NEW.emp_id AND type_id = NEW.type_id
      AND fiscal_year = YEAR(NEW.start_date);
    ELSEIF OLD.status = 'APPROVED' AND NEW.status IN ('CANCELLED','REJECTED') THEN
    UPDATE leave_balances
    SET used_days = GREATEST(0, used_days - NEW.days_count)
    WHERE emp_id = NEW.emp_id AND type_id = NEW.type_id
      AND fiscal_year = YEAR(NEW.start_date);
END IF;
END$$

/* ---- Auto-create leave balances for a new employee ---------------- */



DELIMITER ;

/* =====================================================================
   08. REPORTING VIEWS
   ===================================================================== */

CREATE OR REPLACE VIEW v_employee_directory AS
SELECT e.emp_id, e.emp_code, e.full_name_ar, e.full_name_en, e.gender,
       TIMESTAMPDIFF(YEAR, e.birth_date, CURDATE())        AS age,
       d.name_ar   AS department, j.title_ar AS job_title, j.job_grade,
       b.name_ar   AS branch,     m.full_name_ar AS manager,
       e.hire_date,
       TIMESTAMPDIFF(YEAR, e.hire_date, CURDATE())         AS years_of_service,
       e.emp_status, c.contract_type, c.basic_salary, e.email, e.mobile
FROM employees e
         JOIN departments d ON d.dept_id = e.dept_id
         JOIN job_titles  j ON j.job_id  = e.job_id
         JOIN branches    b ON b.branch_id = e.branch_id
         LEFT JOIN employees m ON m.emp_id = e.manager_id
         LEFT JOIN employee_contracts c ON c.emp_id = e.emp_id AND c.status = 'ACTIVE';

CREATE OR REPLACE VIEW v_payslip_header AS
SELECT p.payslip_id, p.payslip_no, pp.period_code, pp.pay_date,
       e.emp_code, e.full_name_ar, d.name_ar AS department, j.title_ar AS job_title,
       p.basic_salary, p.total_earnings AS gross_pay, p.total_deductions,
       p.insurance_employee, p.income_tax, p.net_pay,
       p.worked_days, p.absent_days, p.overtime_hours,
       p.insurance_employer,
       (p.total_earnings + p.insurance_employer) AS total_company_cost,
       p.status, p.currency
FROM payslips p
         JOIN payroll_periods pp ON pp.period_id = p.period_id
         JOIN employees e  ON e.emp_id  = p.emp_id
         JOIN departments d ON d.dept_id = e.dept_id
         JOIN job_titles  j ON j.job_id  = e.job_id;

CREATE OR REPLACE VIEW v_payslip_detail AS
SELECT pp.period_code, e.emp_code, e.full_name_ar, p.payslip_no,
       l.comp_type, l.comp_code, l.comp_name_ar, l.amount, l.calc_note
FROM payslip_lines l
         JOIN payslips p        ON p.payslip_id = l.payslip_id
         JOIN payroll_periods pp ON pp.period_id = p.period_id
         JOIN employees e       ON e.emp_id = p.emp_id
ORDER BY pp.period_code, e.emp_code, l.comp_type DESC, l.print_order;

CREATE OR REPLACE VIEW v_payroll_cost_by_dept AS
SELECT pp.period_code, d.name_ar AS department, COUNT(*) AS employees,
       ROUND(SUM(p.basic_salary),2)       AS total_basic,
       ROUND(SUM(p.total_earnings),2)     AS total_gross,
       ROUND(SUM(p.income_tax),2)         AS total_tax,
       ROUND(SUM(p.insurance_employee),2) AS insurance_employee,
       ROUND(SUM(p.insurance_employer),2) AS insurance_employer,
       ROUND(SUM(p.net_pay),2)            AS total_net,
       ROUND(SUM(p.total_earnings + p.insurance_employer),2) AS company_cost
FROM payslips p
         JOIN payroll_periods pp ON pp.period_id = p.period_id
         JOIN employees e  ON e.emp_id = p.emp_id
         JOIN departments d ON d.dept_id = e.dept_id
GROUP BY pp.period_code, d.name_ar;

CREATE OR REPLACE VIEW v_leave_balances AS
SELECT e.emp_code, e.full_name_ar, d.name_ar AS department,
       lt.name_ar AS leave_type, lb.fiscal_year,
       lb.entitled_days, lb.carried_forward, lb.used_days, lb.remaining_days
FROM leave_balances lb
         JOIN employees e   ON e.emp_id = lb.emp_id
         JOIN leave_types lt ON lt.type_id = lb.type_id
         JOIN departments d  ON d.dept_id = e.dept_id;

CREATE OR REPLACE VIEW v_leave_requests_log AS
SELECT lr.request_id, e.emp_code, e.full_name_ar, lt.name_ar AS leave_type,
       lr.start_date, lr.end_date, lr.days_count, lr.status,
       a.full_name_ar AS approved_by, lr.applied_on, lr.decided_on, lr.reason
FROM leave_requests lr
         JOIN employees e    ON e.emp_id = lr.emp_id
         JOIN leave_types lt ON lt.type_id = lr.type_id
         LEFT JOIN employees a ON a.emp_id = lr.approver_id;

CREATE OR REPLACE VIEW v_headcount_by_dept AS
SELECT d.code, d.name_ar AS department, b.name_ar AS branch,
       COUNT(e.emp_id) AS headcount,
       SUM(e.gender = 'M') AS males, SUM(e.gender = 'F') AS females,
       ROUND(AVG(TIMESTAMPDIFF(YEAR, e.hire_date, CURDATE())),1) AS avg_service_years,
       ROUND(AVG(fn_current_basic(e.emp_id, CURDATE())),2) AS avg_basic_salary
FROM departments d
         JOIN branches b ON b.branch_id = d.branch_id
         LEFT JOIN employees e ON e.dept_id = d.dept_id AND e.emp_status IN ('ACTIVE','PROBATION')
GROUP BY d.code, d.name_ar, b.name_ar;

CREATE OR REPLACE VIEW v_active_loans AS
SELECT l.loan_id, e.emp_code, e.full_name_ar, l.loan_type, l.principal_amount,
       l.installments_count, l.monthly_installment, l.remaining_balance,
       ROUND(100 * (l.principal_amount - l.remaining_balance) / l.principal_amount, 1) AS paid_pct,
       l.start_period, l.status
FROM loans l JOIN employees e ON e.emp_id = l.emp_id;

/* =====================================================================
   09. SEED DATA
   ===================================================================== */

-- ---- 9.1 payroll settings & tax brackets -----------------------------
INSERT INTO payroll_settings
(fiscal_year, personal_exemption, ins_min_wage, ins_max_wage,
 ins_employee_rate, ins_employer_rate, working_days_month, daily_hours, overtime_factor)
VALUES
    (2025, 20000.00, 2300.00, 14500.00, 11.00, 18.75, 30, 8.0, 1.50),
    (2026, 20000.00, 2600.00, 16000.00, 11.00, 18.75, 30, 8.0, 1.50);

INSERT INTO tax_brackets (fiscal_year, from_amount, to_amount, rate) VALUES
                                                                         (2026,      0.00,   40000.00,  0.00),
                                                                         (2026,  40000.00,   55000.00, 10.00),
                                                                         (2026,  55000.00,   70000.00, 15.00),
                                                                         (2026,  70000.00,  200000.00, 20.00),
                                                                         (2026, 200000.00,  400000.00, 22.50),
                                                                         (2026, 400000.00, 99999999.00, 25.00),
                                                                         (2025,      0.00,   40000.00,  0.00),
                                                                         (2025,  40000.00,   55000.00, 10.00),
                                                                         (2025,  55000.00,   70000.00, 15.00),
                                                                         (2025,  70000.00,  200000.00, 20.00),
                                                                         (2025, 200000.00,  400000.00, 22.50),
                                                                         (2025, 400000.00, 99999999.00, 25.00);

-- ---- 9.2 branches & departments --------------------------------------
INSERT INTO branches (branch_id, code, name_en, name_ar, city, address) VALUES
                                                                            (1,'HQ',  'Head Office',        'المركز الرئيسي',   'Cairo',      '12 Street 90, New Cairo'),
                                                                            (2,'ALX', 'Alexandria Plant',   'مصنع الإسكندرية',  'Alexandria', 'Industrial Zone, Borg El Arab'),
                                                                            (3,'GIZ', 'Giza Warehouse',     'مخازن الجيزة',     'Giza',       '6th of October Industrial Area');

INSERT INTO departments (dept_id, code, name_en, name_ar, parent_dept_id, cost_center, branch_id) VALUES
                                                                                                      (1,'EXEC','Executive Management','الإدارة العليا',        NULL,'CC-1000',1),
                                                                                                      (2,'FIN', 'Finance & Accounting','المالية والحسابات',      1,   'CC-2000',1),
                                                                                                      (3,'HR',  'Human Resources',     'الموارد البشرية',        1,   'CC-3000',1),
                                                                                                      (4,'IT',  'Information Technology','تكنولوجيا المعلومات',  1,   'CC-4000',1),
                                                                                                      (5,'SLS', 'Sales',               'المبيعات',               1,   'CC-5000',1),
                                                                                                      (6,'MKT', 'Marketing',           'التسويق',                5,   'CC-5100',1),
                                                                                                      (7,'OPS', 'Production & Operations','الإنتاج والعمليات',   1,   'CC-6000',2),
                                                                                                      (8,'PRC', 'Procurement',         'المشتريات',              2,   'CC-7000',1),
                                                                                                      (9,'WHS', 'Warehousing & Logistics','المخازن واللوجستيات', 7,   'CC-8000',3),
                                                                                                      (10,'QA', 'Quality Assurance',   'ضمان الجودة',            7,   'CC-9000',2);

-- ---- 9.3 job titles ---------------------------------------------------
INSERT INTO job_titles (job_id, code, title_en, title_ar, job_grade, min_salary, max_salary, is_managerial) VALUES
                                                                                                                (1,'CEO',     'Chief Executive Officer','الرئيس التنفيذي',        'G7',70000,120000,1),
                                                                                                                (2,'CFO',     'Chief Financial Officer','المدير المالي',          'G7',55000, 90000,1),
                                                                                                                (3,'DIR-HR',  'HR Director',            'مدير الموارد البشرية',   'G6',40000, 65000,1),
                                                                                                                (4,'DIR-IT',  'IT Director',            'مدير تكنولوجيا المعلومات','G6',42000, 70000,1),
                                                                                                                (5,'DIR-SLS', 'Sales Director',         'مدير المبيعات',          'G6',40000, 68000,1),
                                                                                                                (6,'DIR-OPS', 'Operations Director',    'مدير العمليات',          'G6',40000, 66000,1),
                                                                                                                (7,'MGR-FIN', 'Finance Manager',        'مدير مالي',              'G5',28000, 45000,1),
                                                                                                                (8,'MGR-HR',  'HR Manager',             'مدير موارد بشرية',       'G5',25000, 42000,1),
                                                                                                                (9,'MGR-IT',  'IT Manager',             'مدير نظم المعلومات',     'G5',28000, 46000,1),
                                                                                                                (10,'MGR-SLS','Sales Manager',          'مدير مبيعات',            'G5',26000, 44000,1),
                                                                                                                (11,'MGR-MKT','Marketing Manager',      'مدير التسويق',           'G5',26000, 44000,1),
                                                                                                                (12,'MGR-PRD','Production Manager',     'مدير الإنتاج',           'G5',27000, 45000,1),
                                                                                                                (13,'MGR-PRC','Procurement Manager',    'مدير المشتريات',         'G5',24000, 40000,1),
                                                                                                                (14,'MGR-WHS','Warehouse Manager',      'مدير المخازن',           'G4',18000, 32000,1),
                                                                                                                (15,'MGR-QA', 'QA Manager',             'مدير الجودة',            'G5',25000, 42000,1),
                                                                                                                (16,'ACC-SR', 'Senior Accountant',      'محاسب أول',              'G3',12000, 22000,0),
                                                                                                                (17,'ACC',    'Accountant',             'محاسب',                  'G2', 8000, 15000,0),
                                                                                                                (18,'HR-SPC', 'HR Specialist',          'أخصائي موارد بشرية',     'G2', 8000, 16000,0),
                                                                                                                (19,'DEV-SR', 'Senior Software Engineer','مهندس برمجيات أول',     'G4',20000, 38000,0),
                                                                                                                (20,'DEV',    'Software Engineer',      'مهندس برمجيات',          'G3',13000, 26000,0),
                                                                                                                (21,'SYSADM', 'System Administrator',   'مسؤول أنظمة',            'G3',12000, 24000,0),
                                                                                                                (22,'SLS-REP','Sales Representative',   'مندوب مبيعات',           'G2', 7000, 14000,0),
                                                                                                                (23,'MKT-SPC','Marketing Specialist',   'أخصائي تسويق',           'G2', 8000, 16000,0),
                                                                                                                (24,'ENG-PRD','Production Engineer',    'مهندس إنتاج',            'G3',12000, 24000,0),
                                                                                                                (25,'TECH',   'Technician',             'فني',                    'G1', 5500, 11000,0),
                                                                                                                (26,'QA-INSP','Quality Inspector',      'مفتش جودة',              'G2', 7000, 14000,0),
                                                                                                                (27,'PRC-SPC','Procurement Specialist', 'أخصائي مشتريات',         'G2', 8000, 15000,0),
                                                                                                                (28,'WHS-KPR','Storekeeper',            'أمين مخزن',              'G1', 5500, 11000,0),
                                                                                                                (29,'DRIVER', 'Driver',                 'سائق',                   'G1', 4500,  9000,0),
                                                                                                                (30,'ADMIN',  'Administrative Assistant','مساعد إداري',           'G1', 5000, 10000,0);

-- ---- 9.4 salary components -------------------------------------------
INSERT INTO salary_components
(comp_id, code, name_en, name_ar, comp_type, calc_type, default_value, is_taxable, is_insurable, is_recurring, print_order) VALUES
                                                                                                                                (1,'BASIC','Basic Salary',       'الراتب الأساسي',     'EARNING','FIXED',    0,1,1,1, 1),
                                                                                                                                (2,'HOUS', 'Housing Allowance',  'بدل سكن',            'EARNING','PCT_BASIC',10,1,0,1, 2),
                                                                                                                                (3,'TRAN', 'Transport Allowance','بدل انتقالات',       'EARNING','FIXED',  800,1,0,1, 3),
                                                                                                                                (4,'MOB',  'Mobile Allowance',   'بدل موبايل',         'EARNING','FIXED',  300,1,0,1, 4),
                                                                                                                                (5,'FOOD', 'Meal Allowance',     'بدل وجبات',          'EARNING','FIXED',  600,0,0,1, 5),
                                                                                                                                (6,'NAT',  'Job Nature Allowance','بدل طبيعة عمل',     'EARNING','PCT_BASIC',7,1,0,1, 6),
                                                                                                                                (7,'SHIFT','Shift Allowance',    'بدل ورديات',         'EARNING','FIXED', 1200,1,0,1, 7),
                                                                                                                                (8,'CAR',  'Car Allowance',      'بدل سيارة',          'EARNING','FIXED', 3500,1,0,1, 8),
                                                                                                                                (9,'COMM', 'Sales Commission',   'عمولة مبيعات',       'EARNING','FIXED',    0,1,0,1, 9),
                                                                                                                                (10,'OT',  'Overtime',           'بدل عمل إضافي',      'EARNING','COMPUTED', 0,1,0,0,10),
                                                                                                                                (11,'INS', 'Social Insurance',   'التأمينات الاجتماعية','DEDUCTION','COMPUTED',0,0,0,1,20),
                                                                                                                                (12,'TAX', 'Income Tax',         'ضريبة كسب العمل',    'DEDUCTION','COMPUTED', 0,0,0,1,21),
                                                                                                                                (13,'ABS', 'Absence Deduction',  'خصم غياب',           'DEDUCTION','COMPUTED', 0,0,0,0,22),
                                                                                                                                (14,'LOAN','Loan Installment',   'قسط سلفة',           'DEDUCTION','COMPUTED', 0,0,0,0,23),
                                                                                                                                (15,'PEN', 'Penalties',          'جزاءات',             'DEDUCTION','FIXED',    0,0,0,0,24),
                                                                                                                                (16,'CLUB','Medical Fund',       'اشتراك الصندوق الطبي','DEDUCTION','FIXED', 150,0,0,1,25),
                                                                                                                                (17,'SYND','Syndicate Fees',     'اشتراك النقابة',     'DEDUCTION','FIXED',   50,0,0,1,26);

-- ---- 9.5 leave types --------------------------------------------------
INSERT INTO leave_types
(type_id, code, name_en, name_ar, annual_quota, is_paid, affects_balance, max_consecutive, requires_attachment, gender_restriction) VALUES
                                                                                                                                        (1,'ANN',  'Annual Leave',    'إجازة سنوية',        21,1,1,15,0,'ANY'),
                                                                                                                                        (2,'SICK', 'Sick Leave',      'إجازة مرضية',        15,1,1,30,1,'ANY'),
                                                                                                                                        (3,'CAS',  'Casual Leave',    'إجازة عارضة',         6,1,1, 2,0,'ANY'),
                                                                                                                                        (4,'UNP',  'Unpaid Leave',    'إجازة بدون أجر',      0,0,0,30,0,'ANY'),
                                                                                                                                        (5,'MAT',  'Maternity Leave', 'إجازة وضع',          90,1,0,90,1,'F'),
                                                                                                                                        (6,'HAJJ', 'Hajj Leave',      'إجازة حج',           30,1,0,30,1,'ANY'),
                                                                                                                                        (7,'MRG',  'Marriage Leave',  'إجازة زواج',          5,1,0, 5,1,'ANY'),
                                                                                                                                        (8,'BRV',  'Bereavement Leave','إجازة وفاة',         3,1,0, 3,0,'ANY');

-- ---- 9.6 employees (35) ----------------------------------------------
-- 9.6.a Executive layer
INSERT INTO employees
(emp_id, emp_code, full_name_ar, full_name_en, gender, birth_date, national_id, marital_status,
 dependents, email, mobile, address, hire_date, dept_id, job_id, branch_id, manager_id,
 emp_status, termination_date, insurance_no, bank_name, bank_account, payment_method) VALUES
                                                                                          (1,'EMP-0001','أحمد سمير عبد العزيز','Ahmed Samir Abdelaziz','M','1972-03-14','27203141201531','MARRIED',3,'a.samir@nile-ind.com','01001234501','التجمع الخامس، القاهرة','2010-01-04',1,1,1,NULL,'ACTIVE',NULL,'INS-100001','CIB','EG380019000500000001234501','BANK'),
                                                                                          (2,'EMP-0002','منى خالد إبراهيم','Mona Khaled Ibrahim','F','1978-07-22','27807221202542','MARRIED',2,'m.khaled@nile-ind.com','01001234502','مدينة نصر، القاهرة','2011-05-15',2,2,1,1,'ACTIVE',NULL,'INS-100002','CIB','EG380019000500000001234502','BANK'),
                                                                                          (3,'EMP-0003','طارق محمود سعيد','Tarek Mahmoud Saeed','M','1980-11-09','28011091203553','MARRIED',2,'t.saeed@nile-ind.com','01001234503','المعادي، القاهرة','2013-02-01',3,3,1,1,'ACTIVE',NULL,'INS-100003','CIB','EG380019000500000001234503','BANK'),
                                                                                          (4,'EMP-0004','هالة عصام فؤاد','Hala Essam Fouad','F','1983-04-18','28304181204564','MARRIED',1,'h.essam@nile-ind.com','01001234504','الشيخ زايد، الجيزة','2014-08-10',4,4,1,1,'ACTIVE',NULL,'INS-100004','QNB','EG380019000500000001234504','BANK'),
                                                                                          (5,'EMP-0005','عمرو ياسر الشناوي','Amr Yasser Elshennawy','M','1981-09-05','28109051205575','MARRIED',3,'a.yasser@nile-ind.com','01001234505','مصر الجديدة، القاهرة','2012-06-01',5,5,1,1,'ACTIVE',NULL,'INS-100005','QNB','EG380019000500000001234505','BANK'),
                                                                                          (6,'EMP-0006','نهى فتحي عبد الله','Noha Fathy Abdallah','F','1979-12-30','27912301206586','MARRIED',2,'n.fathy@nile-ind.com','01001234506','سموحة، الإسكندرية','2012-09-16',7,6,2,1,'ACTIVE',NULL,'INS-100006','NBE','EG380019000500000001234506','BANK');

-- 9.6.b Middle management
INSERT INTO employees
(emp_id, emp_code, full_name_ar, full_name_en, gender, birth_date, national_id, marital_status,
 dependents, email, mobile, address, hire_date, dept_id, job_id, branch_id, manager_id,
 emp_status, termination_date, insurance_no, bank_name, bank_account, payment_method) VALUES
                                                                                          (7,'EMP-0007','كريم عادل منصور','Karim Adel Mansour','M','1986-02-11','28602111207597','MARRIED',2,'k.adel@nile-ind.com','01001234507','مدينة نصر، القاهرة','2016-03-01',2,7,1,2,'ACTIVE',NULL,'INS-100007','CIB','EG380019000500000001234507','BANK'),
                                                                                          (8,'EMP-0008','دينا مصطفى رشاد','Dina Mostafa Rashad','F','1988-06-25','28806251208508','MARRIED',1,'d.mostafa@nile-ind.com','01001234508','الرحاب، القاهرة','2017-07-02',3,8,1,3,'ACTIVE',NULL,'INS-100008','CIB','EG380019000500000001234508','BANK'),
                                                                                          (9,'EMP-0009','محمد جمال الدين حسن','Mohamed Gamaleldin Hassan','M','1987-10-03','28710031209519','MARRIED',3,'m.gamal@nile-ind.com','01001234509','أكتوبر، الجيزة','2016-11-14',4,9,1,4,'ACTIVE',NULL,'INS-100009','QNB','EG380019000500000001234509','BANK'),
                                                                                          (10,'EMP-0010','شريف نبيل حلمي','Sherif Nabil Helmy','M','1985-05-19','28505191210520','MARRIED',2,'s.nabil@nile-ind.com','01001234510','المهندسين، الجيزة','2015-04-05',5,10,1,5,'ACTIVE',NULL,'INS-100010','QNB','EG380019000500000001234510','BANK'),
                                                                                          (11,'EMP-0011','إيمان رأفت زكي','Eman Raafat Zaki','F','1989-08-08','28908081211531','SINGLE',0,'e.raafat@nile-ind.com','01001234511','الدقي، الجيزة','2018-01-15',6,11,1,5,'ACTIVE',NULL,'INS-100011','CIB','EG380019000500000001234511','BANK'),
                                                                                          (12,'EMP-0012','هشام عبد الرحمن عطية','Hisham Abdelrahman Attia','M','1984-01-27','28401271212542','MARRIED',4,'h.attia@nile-ind.com','01001234512','برج العرب، الإسكندرية','2015-10-01',7,12,2,6,'ACTIVE',NULL,'INS-100012','NBE','EG380019000500000001234512','BANK'),
                                                                                          (13,'EMP-0013','ولاء سمير القاضي','Walaa Samir Elkady','F','1987-03-30','28703301213553','MARRIED',2,'w.samir@nile-ind.com','01001234513','حدائق الأهرام، الجيزة','2018-05-20',8,13,1,2,'ACTIVE',NULL,'INS-100013','NBE','EG380019000500000001234513','BANK'),
                                                                                          (14,'EMP-0014','أيمن صبحي غانم','Ayman Sobhy Ghanem','M','1986-09-12','28609121214564','MARRIED',3,'a.sobhy@nile-ind.com','01001234514','أكتوبر، الجيزة','2017-02-06',9,14,3,6,'ACTIVE',NULL,'INS-100014','NBE','EG380019000500000001234514','BANK'),
                                                                                          (15,'EMP-0015','رانيا وجدي سلامة','Rania Wagdy Salama','F','1988-11-21','28811211215575','MARRIED',1,'r.wagdy@nile-ind.com','01001234515','ميامي، الإسكندرية','2018-09-03',10,15,2,6,'ACTIVE',NULL,'INS-100015','NBE','EG380019000500000001234515','BANK');

-- 9.6.c Staff
INSERT INTO employees
(emp_id, emp_code, full_name_ar, full_name_en, gender, birth_date, national_id, marital_status,
 dependents, email, mobile, address, hire_date, dept_id, job_id, branch_id, manager_id,
 emp_status, termination_date, insurance_no, bank_name, bank_account, payment_method) VALUES
                                                                                          (16,'EMP-0016','محمود إسماعيل بدوي','Mahmoud Ismail Badawy','M','1992-04-04','29204041216586','MARRIED',1,'m.ismail@nile-ind.com','01001234516','شبرا، القاهرة','2019-03-10',2,16,1,7,'ACTIVE',NULL,'INS-100016','CIB','EG380019000500000001234516','BANK'),
                                                                                          (17,'EMP-0017','سارة أشرف الديب','Sara Ashraf Eldeeb','F','1995-07-17','29507171217597','SINGLE',0,'s.ashraf@nile-ind.com','01001234517','المعادي، القاهرة','2021-06-01',2,17,1,7,'ACTIVE',NULL,'INS-100017','CIB','EG380019000500000001234517','BANK'),
                                                                                          (18,'EMP-0018','عمر حسام الدين علي','Omar Hosameldin Ali','M','1996-02-23','29602231218508','SINGLE',0,'o.hosam@nile-ind.com','01001234518','حلوان، القاهرة','2022-09-11',2,17,1,7,'ACTIVE',NULL,'INS-100018','CIB','EG380019000500000001234518','BANK'),
                                                                                          (19,'EMP-0019','نور الهدى ماهر','Nour Elhoda Maher','F','1994-10-08','29410081219519','MARRIED',1,'n.maher@nile-ind.com','01001234519','الزيتون، القاهرة','2020-02-17',3,18,1,8,'ACTIVE',NULL,'INS-100019','CIB','EG380019000500000001234519','BANK'),
                                                                                          (20,'EMP-0020','كريم أنور شحاتة','Karim Anwar Shehata','M','1990-12-15','29012151220520','MARRIED',2,'k.anwar@nile-ind.com','01001234520','التجمع الأول، القاهرة','2019-08-25',4,19,1,9,'ACTIVE',NULL,'INS-100020','QNB','EG380019000500000001234520','BANK'),
                                                                                          (21,'EMP-0021','مريم طارق الغندور','Mariam Tarek Elghandour','F','1997-05-06','29705061221531','MARRIED',1,'m.tarek@nile-ind.com','01001234521','مدينة نصر، القاهرة','2022-01-09',4,20,1,9,'ACTIVE',NULL,'INS-100021','QNB','EG380019000500000001234521','BANK'),
                                                                                          (22,'EMP-0022','يوسف عماد الشريف','Youssef Emad Elsherif','M','1998-01-30','29801301222542','SINGLE',0,'y.emad@nile-ind.com','01001234522','فيصل، الجيزة','2024-03-03',4,20,1,9,'ACTIVE',NULL,'INS-100022','QNB','EG380019000500000001234522','BANK'),
                                                                                          (23,'EMP-0023','خالد رمضان سويلم','Khaled Ramadan Soueilem','M','1993-06-14','29306141223553','MARRIED',2,'k.ramadan@nile-ind.com','01001234523','العبور، القليوبية','2021-11-21',4,21,1,9,'ACTIVE',NULL,'INS-100023','QNB','EG380019000500000001234523','BANK'),
                                                                                          (24,'EMP-0024','أحمد فتحي الجندي','Ahmed Fathy Elgindy','M','1995-09-27','29509271224564','SINGLE',0,'a.fathy@nile-ind.com','01001234524','الهرم، الجيزة','2021-03-14',5,22,1,10,'ACTIVE',NULL,'INS-100024','QNB','EG380019000500000001234524','BANK'),
                                                                                          (25,'EMP-0025','ياسمين علاء الحسيني','Yasmin Alaa Elhosseiny','F','1996-11-19','29611191225575','SINGLE',0,'y.alaa@nile-ind.com','01001234525','مصر الجديدة، القاهرة','2023-05-02',5,22,1,10,'ACTIVE',NULL,'INS-100025','QNB','EG380019000500000001234525','BANK'),
                                                                                          (26,'EMP-0026','محمد سعد الطوخي','Mohamed Saad Eltoukhy','M','1994-03-08','29403081226586','MARRIED',1,'m.saad@nile-ind.com','01001234526','الدقي، الجيزة','2022-04-18',6,23,1,11,'ACTIVE',NULL,'INS-100026','CIB','EG380019000500000001234526','BANK'),
                                                                                          (27,'EMP-0027','إبراهيم عبد الستار محمد','Ibrahim Abdelsattar Mohamed','M','1989-07-11','28907111227597','MARRIED',3,'i.abdelsattar@nile-ind.com','01001234527','العامرية، الإسكندرية','2019-01-07',7,24,2,12,'ACTIVE',NULL,'INS-100027','NBE','EG380019000500000001234527','BANK'),
                                                                                          (28,'EMP-0028','مصطفى عادل زهران','Mostafa Adel Zahran','M','1991-02-16','29102161228508','MARRIED',2,'m.adel@nile-ind.com','01001234528','برج العرب، الإسكندرية','2020-06-15',7,25,2,12,'ACTIVE',NULL,'INS-100028','NBE','EG380019000500000001234528','BANK'),
                                                                                          (29,'EMP-0029','سيد عبد المنعم بكري','Sayed Abdelmoneim Bakry','M','1985-08-29','28508291229519','MARRIED',4,'s.bakry@nile-ind.com','01001234529','أبو قير، الإسكندرية','2016-05-03',7,25,2,12,'ACTIVE',NULL,'INS-100029','NBE','EG380019000500000001234529','BANK'),
                                                                                          (30,'EMP-0030','هدى ناصر الشامي','Hoda Nasser Elshamy','F','1993-12-02','29312021230520','SINGLE',0,'h.nasser@nile-ind.com','01001234530','المنتزه، الإسكندرية','2021-09-19',10,26,2,15,'ACTIVE',NULL,'INS-100030','NBE','EG380019000500000001234530','BANK'),
                                                                                          (31,'EMP-0031','طلعت زكريا العايدي','Talaat Zakaria Elaydy','M','1990-05-23','29005231231531','MARRIED',2,'t.zakaria@nile-ind.com','01001234531','إمبابة، الجيزة','2020-10-11',8,27,1,13,'ACTIVE',NULL,'INS-100031','CIB','EG380019000500000001234531','BANK'),
                                                                                          (32,'EMP-0032','حسن عبد الحميد فرج','Hassan Abdelhamid Farag','M','1987-06-07','28706071232542','MARRIED',3,'h.farag@nile-ind.com','01001234532','أكتوبر، الجيزة','2018-12-02',9,28,3,14,'ACTIVE',NULL,'INS-100032','NBE','EG380019000500000001234532','BANK'),
                                                                                          (33,'EMP-0033','رجب سعيد المنشاوي','Ragab Saeed Elmenshawy','M','1983-10-14','28310141233553','MARRIED',5,'r.saeed@nile-ind.com','01001234533','أوسيم، الجيزة','2019-04-01',9,29,3,14,'ACTIVE',NULL,'INS-100033','NBE','EG380019000500000001234533','CASH'),
                                                                                          (34,'EMP-0034','آية محمد سلطان','Aya Mohamed Sultan','F','1999-02-09','29902091234564','SINGLE',0,'a.sultan@nile-ind.com','01001234534','عين شمس، القاهرة','2026-06-15',3,30,1,8,'PROBATION',NULL,'INS-100034','CIB','EG380019000500000001234534','BANK'),
                                                                                          (35,'EMP-0035','مينا نبيل فهمي','Mina Nabil Fahmy','M','1992-08-21','29208211235575','MARRIED',1,'m.nabil@nile-ind.com','01001234535','شبرا الخيمة، القليوبية','2023-02-13',5,22,1,10,'RESIGNED','2026-06-30','INS-100035','QNB','EG380019000500000001234535','BANK');

-- ---- 9.7 contracts ----------------------------------------------------
INSERT INTO employee_contracts
(emp_id, contract_no, contract_type, start_date, end_date, basic_salary, weekly_hours,
 annual_leave_days, probation_months, status, notes) VALUES
                                                         (1,'CT-2010-001','PERMANENT','2010-01-04',NULL,85000.00,40,30,0,'ACTIVE','عقد الرئيس التنفيذي'),
                                                         (2,'CT-2011-002','PERMANENT','2011-05-15',NULL,62000.00,40,30,3,'ACTIVE',NULL),
                                                         (3,'CT-2013-003','PERMANENT','2013-02-01',NULL,48000.00,40,30,3,'ACTIVE',NULL),
                                                         (4,'CT-2014-004','PERMANENT','2014-08-10',NULL,52000.00,40,30,3,'ACTIVE',NULL),
                                                         (5,'CT-2012-005','PERMANENT','2012-06-01',NULL,50000.00,40,30,3,'ACTIVE',NULL),
                                                         (6,'CT-2012-006','PERMANENT','2012-09-16',NULL,47000.00,40,30,3,'ACTIVE',NULL),
                                                         (7,'CT-2016-007','PERMANENT','2016-03-01',NULL,34000.00,40,25,3,'ACTIVE',NULL),
                                                         (8,'CT-2017-008','PERMANENT','2017-07-02',NULL,30000.00,40,25,3,'ACTIVE',NULL),
                                                         (9,'CT-2016-009','PERMANENT','2016-11-14',NULL,36000.00,40,25,3,'ACTIVE',NULL),
                                                         (10,'CT-2015-010','PERMANENT','2015-04-05',NULL,32000.00,40,25,3,'ACTIVE',NULL),
                                                         (11,'CT-2018-011','PERMANENT','2018-01-15',NULL,29000.00,40,21,3,'ACTIVE',NULL),
                                                         (12,'CT-2015-012','PERMANENT','2015-10-01',NULL,33000.00,48,25,3,'ACTIVE',NULL),
                                                         (13,'CT-2018-013','PERMANENT','2018-05-20',NULL,27000.00,40,21,3,'ACTIVE',NULL),
                                                         (14,'CT-2017-014','PERMANENT','2017-02-06',NULL,22000.00,48,21,3,'ACTIVE',NULL),
                                                         (15,'CT-2018-015','PERMANENT','2018-09-03',NULL,28000.00,40,21,3,'ACTIVE',NULL),
                                                         (16,'CT-2019-016','PERMANENT','2019-03-10',NULL,17000.00,40,21,3,'ACTIVE',NULL),
                                                         (17,'CT-2021-017','PERMANENT','2021-06-01',NULL,11000.00,40,21,3,'ACTIVE',NULL),
                                                         (18,'CT-2022-018','PERMANENT','2022-09-11',NULL, 9500.00,40,21,3,'ACTIVE',NULL),
                                                         (19,'CT-2020-019','PERMANENT','2020-02-17',NULL,12000.00,40,21,3,'ACTIVE',NULL),
                                                         (20,'CT-2019-020','PERMANENT','2019-08-25','2022-12-31',20000.00,40,21,3,'EXPIRED','عقد سابق قبل الترقية'),
                                                         (20,'CT-2023-020','PERMANENT','2023-01-01',NULL,30000.00,40,25,0,'ACTIVE','ترقية إلى مهندس برمجيات أول'),
                                                         (21,'CT-2022-021','PERMANENT','2022-01-09',NULL,18000.00,40,21,3,'ACTIVE',NULL),
                                                         (22,'CT-2024-022','FIXED_TERM','2024-03-03','2027-03-02',14000.00,40,21,3,'ACTIVE',NULL),
                                                         (23,'CT-2021-023','PERMANENT','2021-11-21',NULL,16000.00,40,21,3,'ACTIVE',NULL),
                                                         (24,'CT-2021-024','PERMANENT','2021-03-14',NULL, 9000.00,40,21,3,'ACTIVE',NULL),
                                                         (25,'CT-2023-025','PERMANENT','2023-05-02',NULL, 8000.00,40,21,3,'ACTIVE',NULL),
                                                         (26,'CT-2022-026','PERMANENT','2022-04-18',NULL,11000.00,40,21,3,'ACTIVE',NULL),
                                                         (27,'CT-2019-027','PERMANENT','2019-01-07',NULL,18000.00,48,21,3,'ACTIVE',NULL),
                                                         (28,'CT-2020-028','PERMANENT','2020-06-15',NULL, 8000.00,48,21,3,'ACTIVE',NULL),
                                                         (29,'CT-2016-029','PERMANENT','2016-05-03',NULL, 9500.00,48,25,3,'ACTIVE',NULL),
                                                         (30,'CT-2021-030','PERMANENT','2021-09-19',NULL, 9000.00,48,21,3,'ACTIVE',NULL),
                                                         (31,'CT-2020-031','PERMANENT','2020-10-11',NULL,11500.00,40,21,3,'ACTIVE',NULL),
                                                         (32,'CT-2018-032','PERMANENT','2018-12-02',NULL, 7500.00,48,21,3,'ACTIVE',NULL),
                                                         (33,'CT-2019-033','PERMANENT','2019-04-01',NULL, 6000.00,48,21,3,'ACTIVE',NULL),
                                                         (34,'CT-2026-034','FIXED_TERM','2026-06-15','2027-06-14',6500.00,40,21,3,'ACTIVE','تحت الاختبار'),
                                                         (35,'CT-2023-035','PERMANENT','2023-02-13','2026-06-30',8500.00,40,21,3,'ACTIVE','انتهت الخدمة بالاستقالة');

-- ---- 9.8 salary components per employee (rule based) ------------------
-- Housing: 15% for grades G5+, 10% for the rest
INSERT INTO employee_salary_components (emp_id, comp_id, percentage, effective_from, notes)
SELECT e.emp_id, 2, IF(j.job_grade IN ('G5','G6','G7'), 15.00, 10.00),
       GREATEST(e.hire_date, '2024-01-01'), 'بدل سكن حسب الدرجة الوظيفية'
FROM employees e JOIN job_titles j ON j.job_id = e.job_id;

-- Transport: 1,500 for managers / 800 default
INSERT INTO employee_salary_components (emp_id, comp_id, amount, effective_from, notes)
SELECT e.emp_id, 3, IF(j.is_managerial = 1, 1500.00, NULL),
       GREATEST(e.hire_date, '2024-01-01'), 'بدل انتقالات'
FROM employees e JOIN job_titles j ON j.job_id = e.job_id;

-- Mobile allowance: grade G3 and above
INSERT INTO employee_salary_components (emp_id, comp_id, amount, effective_from, notes)
SELECT e.emp_id, 4, NULL, GREATEST(e.hire_date, '2024-01-01'), 'بدل خط موبايل'
FROM employees e JOIN job_titles j ON j.job_id = e.job_id
WHERE j.job_grade IN ('G3','G4','G5','G6','G7');

-- Meal allowance: plant & warehouse staff
INSERT INTO employee_salary_components (emp_id, comp_id, amount, effective_from, notes)
SELECT e.emp_id, 5, NULL, GREATEST(e.hire_date, '2024-01-01'), 'بدل وجبات للمواقع الصناعية'
FROM employees e WHERE e.branch_id IN (2,3);

-- Job nature allowance: production, warehousing, QA
INSERT INTO employee_salary_components (emp_id, comp_id, percentage, effective_from, notes)
SELECT e.emp_id, 6, NULL, GREATEST(e.hire_date, '2024-01-01'), 'بدل طبيعة عمل'
FROM employees e WHERE e.dept_id IN (7,9,10);

-- Shift allowance: technicians, storekeeper, driver
INSERT INTO employee_salary_components (emp_id, comp_id, amount, effective_from, notes)
SELECT e.emp_id, 7, NULL, GREATEST(e.hire_date, '2024-01-01'), 'بدل ورديات'
FROM employees e WHERE e.job_id IN (25,28,29);

-- Car allowance: managerial roles (6,000 for directors and above)
INSERT INTO employee_salary_components (emp_id, comp_id, amount, effective_from, notes)
SELECT e.emp_id, 8, IF(j.job_grade IN ('G6','G7'), 6000.00, NULL),
       GREATEST(e.hire_date, '2024-01-01'), 'بدل سيارة'
FROM employees e JOIN job_titles j ON j.job_id = e.job_id
WHERE j.is_managerial = 1;

-- Sales commission (individual targets)
INSERT INTO employee_salary_components (emp_id, comp_id, amount, effective_from, notes) VALUES
                                                                                            (24, 9, 4500.00, '2025-01-01', 'عمولة حسب تحقيق التارجت'),
                                                                                            (25, 9, 3800.00, '2025-01-01', 'عمولة حسب تحقيق التارجت'),
                                                                                            (35, 9, 2600.00, '2025-01-01', 'عمولة حسب تحقيق التارجت'),
                                                                                            (10, 9, 6000.00, '2025-01-01', 'عمولة إدارة المبيعات');

-- Medical fund: everybody / Syndicate fees: engineers only
INSERT INTO employee_salary_components (emp_id, comp_id, amount, effective_from, notes)
SELECT e.emp_id, 16, NULL, GREATEST(e.hire_date, '2024-01-01'), 'اشتراك الصندوق الطبي' FROM employees e;

INSERT INTO employee_salary_components (emp_id, comp_id, amount, effective_from, notes)
SELECT e.emp_id, 17, NULL, GREATEST(e.hire_date, '2024-01-01'), 'اشتراك نقابة المهندسين'
FROM employees e WHERE e.job_id IN (19,20,21,24);

-- One-off penalties (limited to a single payroll month)
INSERT INTO employee_salary_components (emp_id, comp_id, amount, effective_from, effective_to, notes) VALUES
                                                                                                          (28, 15, 200.00, '2026-07-01', '2026-07-31', 'جزاء مخالفة اشتراطات السلامة'),
                                                                                                          (24, 15, 300.00, '2026-05-01', '2026-05-31', 'جزاء تأخير متكرر');

-- ---- 9.9 leave balances for FY2026 ------------------------------------
INSERT INTO leave_balances (emp_id, type_id, fiscal_year, entitled_days, carried_forward, used_days)
SELECT e.emp_id, lt.type_id, 2026,
       CASE WHEN lt.code = 'ANN' THEN IFNULL(c.annual_leave_days, lt.annual_quota) ELSE lt.annual_quota END,
       CASE WHEN lt.code = 'ANN' THEN MOD(e.emp_id, 5) ELSE 0 END,
       0
FROM employees e
         JOIN leave_types lt ON lt.affects_balance = 1 AND lt.gender_restriction IN ('ANY', e.gender)
         LEFT JOIN employee_contracts c ON c.emp_id = e.emp_id AND c.status = 'ACTIVE'
    ON DUPLICATE KEY UPDATE
                         entitled_days = VALUES(entitled_days), carried_forward = VALUES(carried_forward);

-- ---- 9.10 leave requests (inserted PENDING, then decided -> triggers) --
INSERT INTO leave_requests (request_id, emp_id, type_id, start_date, end_date, days_count, reason, applied_on) VALUES
                                                                                                                   (1, 16,1,'2026-02-09','2026-02-13', 5,'إجازة سنوية - سفر عائلي','2026-01-25'),
                                                                                                                   (2, 17,3,'2026-03-02','2026-03-02', 1,'ظرف عائلي طارئ','2026-03-02'),
                                                                                                                   (3, 20,1,'2026-04-06','2026-04-16',11,'إجازة سنوية','2026-03-15'),
                                                                                                                   (4, 21,5,'2026-04-01','2026-06-29',90,'إجازة وضع','2026-03-10'),
                                                                                                                   (5, 23,2,'2026-05-11','2026-05-14', 4,'إجازة مرضية بتقرير طبي','2026-05-11'),
                                                                                                                   (6, 24,1,'2026-05-18','2026-05-21', 4,'إجازة سنوية','2026-05-05'),
                                                                                                                   (7, 27,1,'2026-05-25','2026-05-28', 4,'إجازة سنوية','2026-05-10'),
                                                                                                                   (8, 28,4,'2026-06-08','2026-06-10', 3,'إجازة بدون أجر','2026-06-01'),
                                                                                                                   (9, 30,3,'2026-06-15','2026-06-16', 2,'إجازة عارضة','2026-06-15'),
                                                                                                                   (10,19,1,'2026-06-21','2026-06-25', 5,'إجازة سنوية','2026-06-07'),
                                                                                                                   (11,32,2,'2026-06-29','2026-07-02', 4,'إجازة مرضية','2026-06-29'),
                                                                                                                   (12,31,7,'2026-07-05','2026-07-09', 5,'إجازة زواج','2026-06-20'),
                                                                                                                   (13,26,1,'2026-07-12','2026-07-16', 5,'إجازة سنوية','2026-06-28'),
                                                                                                                   (14,29,6,'2026-07-01','2026-07-30',30,'إجازة حج','2026-05-30'),
                                                                                                                   (15,18,1,'2026-07-19','2026-07-23', 5,'إجازة سنوية','2026-07-05'),
                                                                                                                   (16,33,4,'2026-07-27','2026-07-29', 3,'إجازة بدون أجر','2026-07-20'),
                                                                                                                   (17,22,1,'2026-08-02','2026-08-06', 5,'إجازة سنوية','2026-07-19'),
                                                                                                                   (18,25,3,'2026-08-10','2026-08-11', 2,'إجازة عارضة','2026-08-10'),
                                                                                                                   (19,30,1,'2026-08-16','2026-08-20', 5,'إجازة سنوية','2026-08-02'),
                                                                                                                   (20,17,1,'2026-08-23','2026-08-27', 5,'إجازة سنوية','2026-08-13'),
                                                                                                                   (21,34,3,'2026-08-24','2026-08-25', 2,'إجازة عارضة','2026-08-20'),
                                                                                                                   (22,23,1,'2026-09-06','2026-09-10', 5,'إجازة سنوية','2026-08-18'),
                                                                                                                   (23,16,2,'2026-08-30','2026-09-01', 3,'إجازة مرضية','2026-08-22');

-- approvals (fire trg_leave_approved -> update balances)
UPDATE leave_requests SET status='APPROVED', approver_id = CASE
                                                               WHEN emp_id IN (16,17,18) THEN 7  WHEN emp_id IN (19,34) THEN 8
                                                               WHEN emp_id IN (20,21,22,23) THEN 9 WHEN emp_id IN (24,25,35) THEN 10
                                                               WHEN emp_id = 26 THEN 11 WHEN emp_id IN (27,28,29) THEN 12
                                                               WHEN emp_id = 31 THEN 13 WHEN emp_id IN (32,33) THEN 14
                                                               WHEN emp_id = 30 THEN 15 ELSE 3 END,
                          decided_on = DATE_ADD(applied_on, INTERVAL 1 DAY)
WHERE request_id IN (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,18,19);

UPDATE leave_requests SET status='REJECTED', approver_id = 9, decided_on = '2026-07-21',
                          reject_reason = 'ذروة تسليم مشروع - يُرجى إعادة الطلب في سبتمبر'
WHERE request_id = 17;

-- requests 20..23 remain PENDING (awaiting approval)

-- ---- 9.11 loans / advances --------------------------------------------
INSERT INTO loans (loan_id, emp_id, loan_type, principal_amount, installments_count,
                   monthly_installment, remaining_balance, start_period, approved_by, status, request_date) VALUES
                                                                                                                (1,17,'ADVANCE',   20000.00,10, 2000.00, 16000.00,'2026-03',2,'ACTIVE','2026-02-20'),
                                                                                                                (2,24,'EMERGENCY', 15000.00, 6, 2500.00, 12500.00,'2026-04',2,'ACTIVE','2026-03-22'),
                                                                                                                (3,28,'PERSONAL',  30000.00,12, 2500.00, 20000.00,'2026-01',2,'ACTIVE','2025-12-15'),
                                                                                                                (4,33,'ADVANCE',    6000.00, 3, 2000.00,  6000.00,'2026-05',3,'ACTIVE','2026-04-19'),
                                                                                                                (5,21,'HOUSING',  100000.00,24, 4166.67, 87500.00,'2026-02',1,'ACTIVE','2026-01-11'),
                                                                                                                (6,16,'ADVANCE',   10000.00, 5, 2000.00,     0.00,'2025-06',2,'CLOSED','2025-05-18');

-- ---- 9.12 payroll periods ---------------------------------------------
INSERT INTO payroll_periods (period_id, period_code, fiscal_year, start_date, end_date, pay_date, working_days, status) VALUES
                                                                                                                            (1,'2026-05',2026,'2026-05-01','2026-05-31','2026-05-28',21,'OPEN'),
                                                                                                                            (2,'2026-06',2026,'2026-06-01','2026-06-30','2026-06-28',22,'OPEN'),
                                                                                                                            (3,'2026-07',2026,'2026-07-01','2026-07-31','2026-07-28',23,'OPEN'),
                                                                                                                            (4,'2026-08',2026,'2026-08-01','2026-08-31','2026-08-27',21,'OPEN');

-- ---- 9.13 monthly attendance summary ----------------------------------
INSERT INTO attendance_summary
(period_id, emp_id, working_days, present_days, paid_leave_days, unpaid_absent_days, overtime_hours, late_minutes)
SELECT period_id, emp_id, working_days,
       working_days - paid_leave - unpaid, paid_leave, unpaid, ot, late
FROM (
         SELECT p.period_id, e.emp_id, p.working_days,
                CASE WHEN MOD(e.emp_id * 7 + p.period_id * 13, 9)  = 0 THEN 2.0
                     WHEN MOD(e.emp_id * 7 + p.period_id * 13, 11) = 5 THEN 1.0
                     ELSE 0 END AS paid_leave,
                CASE WHEN MOD(e.emp_id * 5 + p.period_id * 17, 19) = 0 THEN 1.0
                     WHEN MOD(e.emp_id * 5 + p.period_id * 17, 23) = 7 THEN 0.5
                     ELSE 0 END AS unpaid,
                CASE WHEN j.is_managerial = 0 AND j.job_grade IN ('G1','G2','G3')
                         THEN MOD(e.emp_id * 3 + p.period_id * 7, 26) ELSE 0 END AS ot,
                MOD(e.emp_id * 13 + p.period_id * 29, 75) AS late
         FROM payroll_periods p
                  JOIN employees e   ON e.hire_date <= p.end_date
             AND (e.termination_date IS NULL OR e.termination_date >= p.start_date)
                  JOIN job_titles j  ON j.job_id = e.job_id
     ) x;

/* =====================================================================
   10. RUN THE PAYROLL ENGINE
   ===================================================================== */
CALL sp_run_payroll('2026-05');
CALL sp_run_payroll('2026-06');
CALL sp_run_payroll('2026-07');
CALL sp_run_payroll('2026-08');   -- current month: processed, not paid yet

CALL sp_pay_period('2026-05','TRF');
CALL sp_pay_period('2026-06','TRF');
CALL sp_pay_period('2026-07','TRF');


UPDATE payroll_periods SET status = 'CLOSED' WHERE period_code IN ('2026-05','2026-06');
UPDATE payslips SET status = 'APPROVED'
WHERE period_id = (SELECT period_id FROM payroll_periods WHERE period_code = '2026-08');
